### ISSUE TITLE
Support to get vector from index

### ISSUE THREAD

**Issue by cydrain** [milvus-io/knowhere#194]
Need support to get vector raw data from index:
- [x] BINARY_IDMAP
- [x] BINARY_IVF
- [x] IDMAP
- [x] IVF_FLAT
- [x] IVF_NM
- [x] HNSW
- [x] ANNOY

**Comment by cydrain** [comment]
In Milvus 0.9.0, Milvus supports GetVectorById and QueryById.
But these 2 APIs are disabled since Milvus 1.10.0 with this PR: https://github.com/milvus-io/milvus/pull/2444

**Comment by cydrain** [comment]
For IVF_NM, need get vector data from 'arranged_data' and 'prefix_sum'.
We can refer how Query get vector to calculate distance: 
```
#0  faiss::(anonymous namespace)::IVFFlatScanner<(faiss::MetricType)1, faiss::CMax<float, long> >::scan_codes (this=0x55e5a96621b0, list_size=717, codes=0x7ff87177f410 "", ids=0x55e5a96bba30, simi=0x55e5a9683790, idxi=0x55e5a9683460, k=10, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexIVFFlat.cpp:200
#1  0x00007ff8973bd07f in faiss::IndexIVF::<lambda(faiss::Index::idx_t, float, const uint8_t*, float*, faiss::Index::idx_t*, faiss::BitsetView)>::operator()(faiss::Index::idx_t, float, const uint8_t *, float *, faiss::Index::idx_t *, faiss::BitsetView) const (__closure=0x7ffd9b4cac70, key=12, coarse_dis_i=12.3024368, arranged_codes=0x7ff87140f010 "@\266\206@\252\224\001?\025\251\256>f\301\241><\016\064?jD\035?S\323@?\250\352\006?\271\306\002>\371EJ?E\371\036?\031y\324>\034\276\264>\351\351\063?mz9?3,0?\212\005\263<[\364|>\n'(?\334/\207>J\262\066>\002pm>T\210p?2ڋ>qz&>R\363w?\320\365\214>^\330\024?\306#l>\313\342~?=\376\244>\205\223h?l6\277=\205\227\026>\274Q\306>\005\062o<\311T\027?\226\357\216>\225;\307>鿃>m\034b>\221\275\300>d\247\002>\272\063\213>.6v>ݤ=?D\277\333>\336\302\016?\275c\302=L\t`>\004\273M?\372*\251>\341V\n>lA\202>\341#\300>\305$\267>\025\rG>v\214=>h\210\"?if\306>\331\340e?\367Jz?\fzl?\025\222\070?"..., simi=0x55e5a9683790, idxi=0x55e5a9683460, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexIVF.cpp:929
#2  0x00007ff8973bd9d6 in faiss::IndexIVF::search_preassigned_without_codes (this=0x55e5a9687bd0, n=1, x=0x55e5a9662350, arranged_codes=0x7ff87140f010 "@\266\206@\252\224\001?\025\251\256>f\301\241><\016\064?jD\035?S\323@?\250\352\006?\271\306\002>\371EJ?E\371\036?\031y\324>\034\276\264>\351\351\063?mz9?3,0?\212\005\263<[\364|>\n'(?\334/\207>J\262\066>\002pm>T\210p?2ڋ>qz&>R\363w?\320\365\214>^\330\024?\306#l>\313\342~?=\376\244>\205\223h?l6\277=\205\227\026>\274Q\306>\005\062o<\311T\027?\226\357\216>\225;\307>鿃>m\034b>\221\275\300>d\247\002>\272\063\213>.6v>ݤ=?D\277\333>\336\302\016?\275c\302=L\t`>\004\273M?\372*\251>\341V\n>lA\202>\341#\300>\305$\267>\025\rG>v\214=>h\210\"?if\306>\331\340e?\367Jz?\fzl?\025\222\070?"..., prefix_sum=0x55e5a9660c50, k=10, keys=0x55e5a9683b20, coarse_dis=0x55e5a9677070, distances=0x55e5a9683790, labels=0x55e5a9683460, store_pairs=false, params=0x0, ivf_stats=0x55e5a9683930, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexIVF.cpp:966
#3  0x00007ff8973bc290 in faiss::IndexIVF::<lambda(faiss::Index::idx_t, float const*, const uint8_t*, const size_t*, float*, faiss::Index::idx_t*, faiss::IndexIVFStats*)>::operator()(faiss::Index::idx_t, const float *, const uint8_t *, const size_t *, float *, faiss::Index::idx_t *, faiss::IndexIVFStats *) const (__closure=0x7ffd9b4caf30, n=1, x=0x55e5a9662350, arranged_codes=0x7ff87140f010 "@\266\206@\252\224\001?\025\251\256>f\301\241><\016\064?jD\035?S\323@?\250\352\006?\271\306\002>\371EJ?E\371\036?\031y\324>\034\276\264>\351\351\063?mz9?3,0?\212\005\263<[\364|>\n'(?\334/\207>J\262\066>\002pm>T\210p?2ڋ>qz&>R\363w?\320\365\214>^\330\024?\306#l>\313\342~?=\376\244>\205\223h?l6\277=\205\227\026>\274Q\306>\005\062o<\311T\027?\226\357\216>\225;\307>鿃>m\034b>\221\275\300>d\247\002>\272\063\213>.6v>ݤ=?D\277\333>\336\302\016?\275c\302=L\t`>\004\273M?\372*\251>\341V\n>lA\202>\341#\300>\305$\267>\025\rG>v\214=>h\210\"?if\306>\331\340e?\367Jz?\fzl?\025\222\070?"..., prefix_sum=0x55e5a9660c50, distances=0x55e5a9683790, labels=0x55e5a9683460, ivf_stats=0x55e5a9683930) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexIVF.cpp:742
#4  0x00007ff8973bc811 in faiss::IndexIVF::search_without_codes (this=0x55e5a9687bd0, n=10, x=0x55e5a9662350, arranged_codes=0x7ff87140f010 "@\266\206@\252\224\001?\025\251\256>f\301\241><\016\064?jD\035?S\323@?\250\352\006?\271\306\002>\371EJ?E\371\036?\031y\324>\034\276\264>\351\351\063?mz9?3,0?\212\005\263<[\364|>\n'(?\334/\207>J\262\066>\002pm>T\210p?2ڋ>qz&>R\363w?\320\365\214>^\330\024?\306#l>\313\342~?=\376\244>\205\223h?l6\277=\205\227\026>\274Q\306>\005\062o<\311T\027?\226\357\216>\225;\307>鿃>m\034b>\221\275\300>d\247\002>\272\063\213>.6v>ݤ=?D\277\333>\336\302\016?\275c\302=L\t`>\004\273M?\372*\251>\341V\n>lA\202>\341#\300>\305$\267>\025\rG>v\214=>h\210\"?if\306>\331\340e?\367Jz?\fzl?\025\222\070?"..., prefix_sum=0x55e5a9660c50, k=10, distances=0x55e5a9683790, labels=0x55e5a9683460, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexIVF.cpp:774
#5  0x00007ff89738579f in knowhere::IVF_NM::QueryImpl (this=0x55e5a965ef90, n=10, xq=0x55e5a9662350, k=10, distances=0x55e5a9683790, labels=0x55e5a9683460, config=..., bitset=...) at /home/caiyd/vec/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:335
#6  0x00007ff89738471f in knowhere::IVF_NM::Query (this=0x55e5a965ef90, dataset_ptr=std::shared_ptr<knowhere::Dataset> (use count 1, weak count 0) = {...}, config=..., bitset=...) at /home/caiyd/vec/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp:193
#7  0x000055e5a7ca5b9c in IVFNMTest_ivfnm_basic_Test::TestBody (this=0x55e5a9660d50) at /home/caiyd/vec/knowhere/unittest/test_ivf_nm.cpp:112
```
