### ISSUE TITLE
Replace thirdparty/HNSW with faiss::hnsw

### ISSUE THREAD

**Issue by cydrain** [milvus-io/knowhere#90]
Need test the performance of thirdparty/HNSW and faiss::hnsw,
then decide if it's ok to replace thirdparty/HNSW with faiss::hnsw.

**Comment by cydrain** [comment]
Write faiss::HNSW testcase, but it always panic when search, don't know why.
unittest/benchmark/benchmark_faiss_test.cpp::Benchmark_faiss::TEST_HNSW

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f63f951f7f1 in __GI_abort () at abort.c:79
#2  0x00007f63f9568837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f63f9695a7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f63f956f8ba in malloc_printerr (str=str@entry=0x7f63f96977a8 "double free or corruption (!prev)") at malloc.c:5342
#4  0x00007f63f9576e5c in _int_free (have_lock=0, p=0x56032efef520, av=0x7f63f98cac40 <main_arena>) at malloc.c:4311
#5  __GI___libc_free (mem=0x56032efef530) at malloc.c:3134
#6  0x000056032cf24e9a in __gnu_cxx::new_allocator<unsigned char>::deallocate (this=0x7ffcf548c670, __p=0x56032efef530 "\253t\006") at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x000056032cf24655 in std::allocator_traits<std::allocator<unsigned char> >::deallocate (__a=..., __p=0x56032efef530 "\253t\006", __n=1000000) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x000056032cf2355c in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_deallocate (this=0x7ffcf548c670, __p=0x56032efef530 "\253t\006", __n=1000000) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x000056032cf5e941 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::~_Vector_base (this=0x7ffcf548c670, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x000056032cf5d2c9 in std::vector<unsigned char, std::allocator<unsigned char> >::~vector (this=0x7ffcf548c670 = {...}, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007f63fb1337ec in faiss::VisitedTable::~VisitedTable (this=0x7ffcf548c670, __in_chrg=<optimized out>) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/impl/AuxIndexStructures.h:247
#12 0x00007f63fb1405e8 in faiss::IndexHNSW::search (this=0x56032ef5f5b0, n=0, x=0x7ffcf548c7a0, k=51539607552, distances=0x7f63fb1405e8 <_ZNK5faiss9IndexHNSW6searchElPKflPfPlNS_10BitsetViewE._omp_fn.1(void)+1250>, labels=0x7ffcf548c6e0, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexHNSW.cpp:305
#13 0x00007f63f7017edf in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#14 0x00007f63fb13c720 in faiss::IndexHNSW::search (this=0x56032ef70a10, n=10000, x=0x7f63bc093010, k=10, distances=0x56032ef75590, labels=0x56032ef73640, bitset=...) at /home/caiyd/vec/knowhere/thirdparty/faiss/faiss/IndexHNSW.cpp:303
#15 0x000056032cf283ae in Benchmark_faiss::test_hnsw (this=0x56032ef1cb80, M=8, efConstruction=100, nqs=std::vector of length 1, capacity 1 = {...}, topks=std::vector of length 1, capacity 1 = {...}, efs=std::vector of length 5, capacity 5 = {...}) at /home/caiyd/vec/knowhere/unittest/benchmark/benchmark_faiss_test.cpp:352
```
